<?php
/**
 * Created by PhpStorm.
 * User: PGF
 * Date: 2017/4/20
 * Time: 23:11
 */

namespace GFPHP\Model;


use GFPHP\DataObject;
use GFPHP\Model;

/**
 * 用户授权,自动完成账号密码验证,以及登陆验证
 * Class Authorize
 * @package GFPHP\Model
 */
abstract class Authorize extends Model
{
    /**
     * @var bool | array
     */
    protected $account = false;

    /**
     * 账户名字段,用于登陆校验,可是多个字段
     * @var array
     */
    protected $account_field = ['user_name'];

    /**
     * 账户密码,用于校验以及生产HASH密码
     * @var string
     */
    protected $password_field = 'user_password';

    /**
     * 登陆校验的TOKEN名称
     * @var string
     */
    protected $token_name = 'MEMBER_TOKEN';

    /**
     * 重写保存
     * @param array $data
     * @param bool $primary_key
     * @return bool|int|array
     */
    public function save($data, $primary_key = false)
    {
        if (isset($data[$this->password_field]))
            $data[$this->password_field] = password_hash($data[$this->password_field]);
        return parent::save($data, $primary_key); // TODO: Change the autogenerated stub
    }

    /**
     * @param $account
     * @return bool|DataObject
     */
    public function getAccount($account_name)
    {
        $field_counter = 0;
        foreach ($this->account_field as $field) {
            if ($field_counter == 0)
                $this->where($field, $account_name);
            else
                $this->orWhere($field, $account_name);
            $field_counter++;
        }
        return $this->getOne();
    }

    /**
     * 根据用户账号和密码登陆
     * @param string $account
     * @param string $password
     * @return array|boolean
     */
    public function getToken($account, $password)
    {
        $account = $this->getAccount($account);
        if (!$account)
            return false;
        $hash_password = $account[$this->password_field];
        if (password_verify($password, $hash_password)) {
            $token = $account . ' || ' . md5($hash_password);
            return $token;
        } else {
            return false;
        }
    }

    /**
     * 验证token是否正确,正确返回账户信息,否则返回false
     * @param string|bool $token
     * @return array|DataObject|bool
     */
    public function checkToken($token)
    {
        if (!$token)
            return false;
        $token = explode(' || ', base64_decode($token));
        if (count($token) != 2) {
            return false;
        }
        //-- 获取账户信息
        $account = $this->getAccount($token[0]);
        if (!$account)
            return false;
        if ($account) {
            $hash_password = md5($account[$this->password_field]);
            if ($hash_password == $token[1]) {
                return $account;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }
}